# Generated by Django 2.0.5 on 2018-05-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('trade_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bse_no', models.CharField(max_length=10)),
                ('nse_no', models.CharField(max_length=10)),
                ('validity', models.DateField()),
                ('Tax', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('pan', models.CharField(max_length=10)),
                ('virt_money', models.FloatField(default=25000)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('residence', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Owns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('cust_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mk.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('isin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('equity_name', models.CharField(max_length=10)),
                ('prev_close', models.FloatField(default=0.0)),
                ('today_open', models.FloatField(default=0.0)),
                ('today_close', models.FloatField(default=0.0)),
                ('current_rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('trans_date', models.DateField()),
                ('buy_avg', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('buy_value', models.FloatField(default=0.0)),
                ('trans_tax', models.FloatField(default=0.0)),
                ('brokerage', models.FloatField(default=0.0)),
                ('buyer_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_buyer_id', to='mk.Customer')),
                ('isin2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mk.Stocks')),
                ('seller_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_seller_id', to='mk.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='owns',
            name='isin2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mk.Stocks'),
        ),
    ]
