# Generated by Django 2.0.5 on 2018-05-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mk', '0004_auto_20180513_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='today_close',
        ),
        migrations.AddField(
            model_name='stocks',
            name='today_high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='today_low',
            field=models.FloatField(default=0.0),
        ),
    ]
