# Generated by Django 2.0.5 on 2018-05-13 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mk', '0006_auto_20180513_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='bse_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='broker',
            name='nse_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='broker',
            name='trade_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pan',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='equity_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='isin',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
