# Generated by Django 2.0.5 on 2018-05-20 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mk', '0007_auto_20180513_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_rate', models.FloatField(default=0.0)),
                ('ask_quantity', models.FloatField(default=0.0)),
                ('isin2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mk.Stocks')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
