# Generated by Django 2.0.5 on 2018-05-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mk', '0009_order_cust_id2'),
    ]

    operations = [
        migrations.AddField(
            model_name='owns',
            name='buy_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
